### ISSUE TITLE
Django fatal error on runserver

### ISSUE THREAD

**Issue by MattiaPrimavera** [cappuccino-app/cappuccino-server#1]

**Comment by yvan-sraka** [comment]
@MattiaPrimavera How do you solve it :open_mouth:? Which **commit**?

**Comment by MattiaPrimavera** [comment]
I looked back into the history of commits and I did nothing actually, so I'd say we just did not correctly activate the virtual environment ... As I said ... I remembered I stopped coding this while having a working version ...
