### ISSUE TITLE
Fix code indents and whitespaces

### ISSUE THREAD

**Issue by yvan-sraka** [cappuccino-app/cappuccino-server#22]

**Comment by yvan-sraka** [comment]
Done => https://github.com/cappuccino-app/cappuccino-server/commit/2a4f646dc581ba46bf0db3b45a8d82558d6f8b33 :wink:!

**Comment by MattiaPrimavera** [comment]
Ehi there beau gosse maybe u should make a post prepush hook to apply your
indent fix automatically ...

**Comment by yvan-sraka** [comment]
I just use `autopep8`, I let you add this feature :smile:!

**Comment by MattiaPrimavera** [comment]
Make a ticket, write me the exact command u used pls ...

T as reussi a tester? La j ai pas eu le temps mais pour demarrer:
- active ton env
source env/bin/activate
- lance django serv
Python manage.py runserver ...

Puis go to the given address in ur web browser to use cappuccino-client

**Comment by yvan-sraka** [comment]
> Make a ticket, write me the exact command you used please ...

Okay.

> You succeed to test ?

Yes I succeed to test it, look at my last commit!

>  Next go to the given address in your web browser to use cappuccino-web

Hum..

**Comment by MattiaPrimavera** [comment]
It means localhost:8000 come on mate u already started a django serv :) les
wrappers font tt oublier!

**Comment by MattiaPrimavera** [comment]
Si tu veux on p faire un run.sh cmm ca t te sentira a la maison :p
