### ISSUE TITLE
Make install script build pass on Travis CI with Python 3.5

### ISSUE THREAD

**Issue by yvan-sraka** [cappuccino-app/cappuccino-server#35]

**Comment by yvan-sraka** [comment]
Need to fix https://github.com/cappuccino-app/cappuccino-server/issues/37 first!
And let script detect which version of python is running to install the right `requirementsX.X.txt` file?

**Comment by MattiaPrimavera** [comment]
Totally agreed ... but weren't you saying we'll actually replace the install.sh with a more proper Travis install procedure?

**Comment by yvan-sraka** [comment]
Done :wink:!
