### ISSUE TITLE
Fix Travis CI last build!

### ISSUE THREAD

**Issue by yvan-sraka** [cappuccino-app/cappuccino-server#37]

**Comment by yvan-sraka** [comment]
https://travis-ci.org/cappuccino-app/cappuccino-server/jobs/153719244
```shell
django.db.utils.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
```

**Comment by yvan-sraka** [comment]
How do we fix that last time?

**Comment by MattiaPrimavera** [comment]
Insn't it `node_packages` installation the problem here? If that is the case I have the same error on my local, which is solved by running the command with `sudo priviledges`

**Comment by yvan-sraka** [comment]
Done :wink:!
