### ISSUE TITLE
What's default login IDs?

### ISSUE THREAD

**Issue by yvan-sraka** [cappuccino-app/cappuccino-server#38]

**Comment by MattiaPrimavera** [comment]
They're the ones inserted by creating a django super user, it should be
explained in the readme.md ...

**Comment by MattiaPrimavera** [comment]
To be more precise:
```bash
python manage.py createsuperuser --username=admin_user --email=admin@cappuccino.com
```

this is the line I was referring to, which says that the username is ***admin_user*** while the password is asked you when running this command if manually installing and it's the same used for mysql database by default is using automatic install.
